### This is the config file for comparative_degeneracy ###

# odom_ref is your most robust odometry estimate, ideally your output from sensor fusion.
# Degenerate odoms will default pose to this value when they come back online.

odom_ref: reference/odom

# Accepts up to 9 (nav_msgs/Odometry) inputs for odom* but a minimum of 3 is nessescary 
# for degen_detector to function

odom0: example0/odom
odom1: example1/odom
odom2: example2/odom
